Sub CATMain()

Dim editor1 As Editor
Set editor1 = CATIA.ActiveEditor

Dim selection1 As Selection
Set selection1 = editor1.Selection

FEA_ANS = MsgBox("Did you remove FEA Mesh?", vbYesNo)
    If FEA_ANS = vbNo Then
    MsgBox ("First remove Mesh")
    End
    End If

Ext_ref = MsgBox("Did you isolate ext ref?", vbYesNo)
    If Ext_ref = vbNo Then
    MsgBox ("Select Ext ref features and use Isolate_link Macro")
    End
    End If


selection1.Search "CATPrtSearch.Wireframe,all"
Set visPropertySet1 = selection1.VisProperties
visPropertySet1.SetShow 1

selection1.Search "CATPrtSearch.AxisSystem,all"
Set visPropertySet1 = selection1.VisProperties
visPropertySet1.SetShow 1

selection1.Search "CATPrtSearch.Point,all"
Set visPropertySet1 = selection1.VisProperties
visPropertySet1.SetShow 1

selection1.Search "CATPrtSearch.Sketch,all"
Set visPropertySet1 = selection1.VisProperties
visPropertySet1.SetShow 1

selection1.Search "CATPrtSearch.Plane,all"
Set visPropertySet1 = selection1.VisProperties
visPropertySet1.SetShow 1




End Sub
